/**
 * @buildpad/utils
 * 
 * Utility functions for Buildpad UI packages.
 * Includes field interface mapping, value formatting, and validation helpers.
 */

// Field Interface Mapper
export {
  getFieldInterface,
  getFieldDefault,
  getFieldValidation,
  formatFieldValue,
  isFieldReadOnly,
  isUUIDAutoGenerated,
  hasAutoGeneratedDefault,
  getAutoGenerationType,
  isPresentationField,
  type InterfaceType,
  type InterfaceConfig,
  type FieldReadOnlyOptions,
} from './field-interface-mapper';

// Interface Types
export type {
  FieldType,
  LocalType,
  InterfaceGroup,
  InterfaceProps,
  InterfaceOption,
  InterfaceOptionMeta,
  InterfaceDefinition,
  InterfaceMetadata,
  InterfaceRegistrationInput,
  InterfaceGroupDefinition,
} from './interface-types';

// Interface Registry
export {
  InterfaceRegistry,
  interfaceRegistry,
  getInterfaceRegistry,
} from './interface-registry';

// Define Interface Helper
export {
  defineInterface,
  defineInterfaces,
  createInterfaceOption,
  createOptionGroup,
  InterfaceOptions,
  type DefineInterfaceConfig,
} from './define-interface';

// Load Interfaces from Registry
export {
  loadInterfacesFromRegistry,
  extractInterfaceFromComponent,
  getInterfacesForApi,
  type RegistryComponent,
  type RegistryComponentInterface,
  type RegistryJson,
} from './load-interfaces';

// New Item Detection
export { isNewItem, isExistingItem } from './is-new-item';
